### ISSUE TITLE
cmd - loop.cmd 문제

### ISSUE THREAD

**Issue by nnnlog** [HmHmmHm/MyDearest#2]
@HmHmmHm  loop.cmd 를 실행 시에 서버(콘솔)이 무한히 뜹니다

**Comment by wsj7178** [comment]
콘솔만 뜨나요? 아니면 에러메세지 같은거도 같이뜨나요?
혹시 사진도 같이 올려주실 수 있으신지

**Comment by nnnlog** [comment]
@wsj7178 동영상 첨부하려고 했는데, 메모리가 견디지 못해서 꺼집니다
에러메시지는 전혀 뜨지 않습니다(뜬다면, 제니시스 중복 실행 시에 뜨는 메시지)
콘솔은 정상적으로 잘 됩니다. 무한 반복 된다는 점만 빼면요...
한번 동영상으로 찍어보겠습니다

**Comment by nnnlog** [comment]
@wsj7178 @HmHmmHm http://sorisem4106.blog.me/220827868359
동영상 걸어놨으니 봐주세요
사진은 프로세스 종료하면 다 날아가서 안될 것 같습니다

**Comment by wsj7178** [comment]
오류 뜨는데요..?
bin 폴더에 pocketmine.ico 파일 넣어주세요(없으면 적당한 아이콘 사진 하나)

**Comment by nnnlog** [comment]
@wsj7178 그래도 실행은 되더군요.
저기서는 콘솔 오류를 볼 게 아니라 무한 반복이 된다는 것을 보여주는 것입니다
한번 넣어보겠습니다(무섭습니다)
